<?php
return array(
    'map' => array(
        '0' => array('orange' => 'default'),
        '1' => array('ring' => 'default'),
        '2' => array('bar' => 25),
        '3' => array('bar' => 50),
        '4' => array('apple' => 'default'),
        '5' => array('apple' => 2),
        '6' => array('mango' => 'default'),
        '7' => array('watermelon' => 'default'),
        '8' => array('watermelon' => 2),
        '9' => array('goodluck1' => 'default'),
        '10' => array('apple' => 'default'),
        '11' => array('orange' => 2),
        '12' => array('orange' => 'default'),
        '13' => array('ring' => 'default'),
        '14' => array('seven' => 2),
        '15' => array('seven' => 'default'),
        '16' => array('apple' => 'default'),
        '17' => array('mango' => 2),
        '18' => array('mango' => 'default'),
        '19' => array('star' => 'default'),
        '20' => array('star' => 2),
        '21' => array('goodluck2' => 'default'),
        '22' => array('apple' => 'default'),
        '23' => array('ring' => 2),
    ),
);